sudo: required
dist: trusty
group: deprecated-2017Q4
language: generic
services:
- docker
jobs:
  include:
  - stage: amd64
    script:
    - docker pull nhos/ubuntu-defaults-image:latest
    - docker run --env BUILDARCH=amd64 --env BUILDFLAVOUR=gnome-nightly --rm -it -v
      `pwd`:`pwd` -w `pwd` --name buildamd64 --privileged nhos/ubuntu-defaults-image
      /bin/bash -c "./build.sh"
  - stage: i386
    script:
    - docker pull nhos/ubuntu-defaults-image:latest
    - docker run --env BUILDARCH=i386 --env BUILDFLAVOUR=gnome-nightly --rm -it -v
      `pwd`:`pwd` -w `pwd` --name buildi386 --privileged nhos/ubuntu-defaults-image
      /bin/bash -c "./build.sh"
env:
  global:
  - secure: XRjmzFJObjOEXWj43730QHgBc3UnwR7k6H5dwud0WYFdSY4ai0w63O2wYgkT/gfYGgMuLSzqNIHrI6ugOfhvJxt1PavqSkw/+sAfsRicwOmvPKur2g535onBXkpuflA6kor+tGoEviGAvD+g6a0LM/pT2oHBkJU1s/jTDE6eXvbOF7Cof5VTrYC4Ff8hhSy+ArV0U3gjCPok4/fVtA6fpXdyCaEWvShUEXKZf9xet+xG4+MKBdFivD+95ym3sfY+JElNhFM1mPVgbs0t4xDa72dXyC9+KLc455bhyERfkUrOEpeubI9MHlrgS20yO6FVLCjAGYHd2Nv3MgLnLdPZ1pwLEkefBlgSC0aNdXOAujc+Zd+9MRMLxhTAKczZZXnhqtuSxrSWiVZgc3smKoiDfBwRfylfj4C8ONLXGwkjticWm1porbURGgVDkV85/Ez2malDfiQNiax71lJ9p1YdJj/LKJihYVFgdH/f1JB3qcKE8Xd3g3kfxySszBABoRTcA9p0il8t5q+gLGfrMCau/U942SmrsJ7YLw23Pt2HB8VnCLFaQTuX8pEt34FL+z24L7LXoClQDKFZ5W1blhB2gb9m8bldVGucnJYrzLU4SBKKXr4sZ9UlnGw+KK832gWsYh8qKJajslLIIPFqGW2eKqO8GyrEweBsCzbc7M9FBrI=
  - secure: KJU4rSHDrZpVws0yKHMpeprlJr/DAPJKx9SmGePAjCSeybsmqrBA9BHMGNPn+dGI+DrujcIyOcjUESOUEAeLVo4HvgU2DMVJKRC/bnnai/4ZUsmDOJMTCnjjtuWhqIOO+Wb/Ig5heTXu1uGI8CxZetSD2AtxYvychXTmtSEfsNUIlk7psIo147d/nk4vP4ZuumEZrrXqhGPdsNh8hOApeOZaF6Mxw2qZFG8J1uek9W3H5CYUl+LRcFJoM/fJCGl5h3ACJoUQjlsw/+KyFsxDkF49c5PJjxsl0+dPUpBrBR332Vbrq+jAj3n/p3AA0H0jFqx8fd8CMpyROXh5vL4AMaXwi0yORtHDYARE3kmFPKg6Y1aCYTiKAp/CqzOqu6Q2Z0y/oqq5tOaolsX0YcfTs8JhyEfPyaFo5Q/fpBMEhg44zFU6mAW39S2iopwnuhyuBs8KVJJoHmEWrxpLAe/yy9/wvZkzVwPZ1CkwfOJvEXaA3j0pTiDN7Gvig9XVfN61sGf1RHqpQ5GnQ0Ox6oXAsmI7kZHLgm88EzQmCv72nr4/tNSHAKgAwWF46NZY4qFrI2Iu/P0Jq0jgeYmIRxA953t8g/YZgt+IKu4617aBxSC3MdzipvyA9zRGivXUJ78JelNSm4GNpnR6b9fNtm/J8kf/9qrOXoZ+GRZSsNzudn0=
after_success:
- openssl aes-256-cbc -K $encrypted_11d07880bc5f_key -iv $encrypted_11d07880bc5f_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- scp -o stricthostkeychecking=no NHoS-*-amd64*-binary* $BUILDUSER@$BUILDHOST:/mnt/ISO/amd64
- scp -o stricthostkeychecking=no NHoS-*-i386*-binary* $BUILDUSER@$BUILDHOST:/mnt/ISO/i386
- ssh $BUILDUSER@$BUILDHOST '~/gnome-nightly.sh'
notifications:
  slack:
    secure: SQ6JWjCWk1YB5wTZ3Q+tRvyj82/NeCmAvC+afJPhKr8rXYAhN3Q/fMT35nMOHUD4HfgYT3Is/yl4rkS1L7Oqv9ZSaqTKU/XOC2uPuRiVj6kR1+HjfF0WY89zDOV4YY2/P4bjYi/8TxcdlPFqAnWpueQ+1YvQtKA72dGTNJvAdWwHMUnuwYj/wN8ybLzecXjA5vvPH2lRVzKrz939T4ezPc/xL28J1V/EG7v+Wji4OShv4WSriG9tOuSwj+L7xHmFX658b2n++G9epV3DzvYjPz3srFlbAY+3+YT9LaWAvCa5M1DOV5P8UmzHhNKRtjzHQdYvCaHs9vMxCoi/5hCQ4FHis7WX789WV0Ow9n3i29PuYsJvK7iI6ejMXAZVxISEt320PUQlTY7CgTa1A9cwaK9etOoCyIGuFGwRvvTVGiBSTsi8Ke16hfounzkQT8PqKkujY61Yi8LFPvbvGVZfBMtt7N8QIbfqcKvnWUIgtMJw227ITbttrCGHsPIuAU6ed7BuWlTDBzdOjeIFlDD+ONFl5yQ4LzvLxvUh6eD7CO/PO+Cgby04/zwCrSA0pWFVSCkjL8iRgzAWvuIC0e78vRK++anUllSeekHjK+EVfyx5jaz5Xi0eUHb70HcIvAl4Hp1AJ6Oa9tCq7MxB43CnDGd8rwlgW2/DT0ToxXsngq8=
